import type { Config } from "tailwindcss";

const plex = ["IBM Plex Sans", "IBM Plex Sans KR", "sans-serif"];
const hanken = ["Hanken Grotesk", "IBM Plex Sans KR", "sans-serif"];

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#cee5ff",
        "on-primary-fixed-variant": "#33495d",
        "outline-variant": "#c3c7cd",
        "tertiary-container": "#00282e",
        "on-tertiary-container": "#4a95a3",
        error: "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#a1cbf0",
        "secondary-container": "#afd9fe",
        "on-surface-variant": "#43474c",
        "on-tertiary-fixed": "#001f24",
        background: "#f8f9fb",
        primary: "#000f1d",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#88d2e0",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        "secondary-fixed": "#cbe6ff",
        "on-tertiary-fixed-variant": "#004e59",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#778da4",
        "primary-fixed-dim": "#b2c9e2",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-tint": "#4b6176",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        outline: "#73777d",
        "primary-container": "#0d2538",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        surface: "#f8f9fb",
        "on-secondary-container": "#345f7f",
        "surface-bright": "#f8f9fb",
        secondary: "#376282",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        tertiary: "#001014",
        "on-primary-fixed": "#041d30",
        "inverse-primary": "#b2c9e2",
        "tertiary-fixed": "#a4eefd",
        "on-secondary-fixed": "#001e30",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#1c4a69",
        // DESIGN.md 전용 토큰
        teal: "#2E7D8A",
        crimson: "#A63A2A",
        spruce: "#2B5E54",
        "spruce-bg": "#E8F2EF",
        hairline: "#DCE2E6",
        "quote-bg": "#EDF2F6",
        "quote-zone": "#F8FAFC",
      },
      // DESIGN.md: 모서리 0 (원형 full만 예외)
      borderRadius: { DEFAULT: "0", none: "0", sm: "0", md: "0", lg: "0", xl: "0", "2xl": "0", full: "9999px" },
      spacing: {
        "space-xs": "0.25rem",
        "space-xl": "2.25rem",
        "margin-desktop": "2.5rem",
        gutter: "1.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
      },
      boxShadow: { flat: "0 4px 0 0 rgba(13,37,56,0.08)" },
      fontFamily: {
        "headline-lg": hanken,
        "label-sm": plex,
        "headline-md": hanken,
        "headline-sm": hanken,
        "display-lg": hanken,
        "label-md": plex,
        "code-citation": plex,
        "legal-article": plex,
        "body-sm": plex,
        "display-lg-mobile": hanken,
        "body-lg": plex,
        "body-md": plex,
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "code-citation": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "legal-article": ["13px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
